central:
  reports:
    datastores:
      - artifact://kitsuyui/bittersweet/octocov-report
      - artifact://kitsuyui/ts-playground/octocov-report
      - artifact://kitsuyui/react-playground/octocov-report
      # - artifact://owner/other-repo
      # - artifact://owner/another-repo
  badges:
    datastores:
      - local://badges
  push:
    enable: true
