name: Collect

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,3,6,9 * * *'

concurrency:
  group: collect
  cancel-in-progress: false

permissions:
  actions: read
  contents: write

jobs:
  collect:
    name: Collect code metrics using octocov central mode
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check octocov report artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: bash .github/scripts/check-octocov-artifacts.sh

      - name: Run octocov
        uses: k1LoW/octocov-action@a167dc0dee441b7ffc45e1b862ab55ec0d87f278 # v1.5.2

      - name: Check badge freshness
        run: bash .github/scripts/check-badge-freshness.sh
