name: Collect

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,3,6,9 * * *'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write

jobs:
  collect:
    name: Collect code metrics using octocov central mode
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check octocov report artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: bash .github/scripts/check-octocov-artifacts.sh

      - name: Run octocov
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1.5.1
